### ISSUE TITLE
Question: How to Output results to Array

### ISSUE THREAD

**Issue by PythonDevOp** [wdavidw/node-csv-parse#116]
I am looking to parse a CSV file, get the headers, and stick the headers in an array to use later on. How do I perform such an action? Here is what I have so far, but it doesn't seem to do anything:
```
const fs = require('fs');
const parse = require('csv-parse');
const file = "my file path";

let dest = [];
const content = fs.readFileSync(file, 'utf8').toString();

parse(content, {}, function(err, output){
    console.log(output[0]);
    dest.push(output)
});
console.log("the dest", dest)
```
The console.log(output[0] displays a result in the console, but there isn't any data sent to the dest array. Am I using this incorrectly?

**Comment by wdavidw** [comment]
dest is null because this code is run asynchronously. at the time you call `console.log("the dest", dest)`, no parsing was done yet. If you need the parser to run synchronously, you should require "csv-parse/lib/sync". Look at the [tests](https://github.com/wdavidw/node-csv-parse/blob/master/test/api.sync.coffee) or [sample](https://github.com/wdavidw/node-csv-parse/blob/master/samples/sync.js).

**Comment by PythonDevOp** [comment]
Thanks! I appreciate the quick turnaround.
