### ISSUE TITLE
Read ints with leading zeroes as string

### ISSUE THREAD

**Issue by petermanser** [wdavidw/node-csv-parse#56]
Looks like the parsing of ints with leading zeroes as string doesn't work.

``` CoffeeScript
if (@options.auto_parse and @regexp_int.test(@field))
    @line.push parseInt(@field)
else if (@options.auto_parse and @regexp_float.test(@field))
    @line.push parseFloat(@field)
```

Since the dot in the tested text is optional, it does also match strings like `01`.

```
/^(\-|\+)?([0-9]+(\.[0-9]+)?([eE][0-9]+)?|Infinity)$/
```

I think the dot should be not be optional, since we've tested for ints before. Or if still wanted, a leading `0` should only be allowed if it's followed by a `.`.

I'm not sure why this test works:
https://github.com/wdavidw/node-csv-parse/blob/master/test/options.auto_parse.coffee#L53

What do you think?

Thanks!

**Comment by wdavidw** [comment]
I've been doing some googling and code checking.

1. you're right, the tests shouldn't have worked, i fixed a bug where the last column wasn't parsed.
2. the regexp to correctly parse float is ok to write but a nightmare to read, there are a lot of conditions
3. jquery has a sweet way to handle it, without a regex
4. using jquery strategy involves accepting trailing 0, which is fine with me
5. using jquery strategy mean that now "regexp_int" and "regexp_float" can be a regexp or a function, so I renamed them "is_int" and "is_float"

**Comment by petermanser** [comment]
Thanks for your fast reply. So you plan to move to this jquery strategy?

About the regex (2): I don't agree it is correct for the CSV parse use case, see here: http://regexr.com/3bg7t ... but it's not that easy. :wink:

**Comment by wdavidw** [comment]
you right, the complicate regexp i mentionned was with handler the trailing 0. the idea is that we would have the choice between regexp and user defined function

**Comment by kevinob11** [comment]
According to [this stack overflow](http://stackoverflow.com/questions/34595812/is-a-csv-with-equal-sign-valid) a common (I've tested this works in excel and google drive) way of handling leading zeros is to put an equals sign before the initial quote for the field (EG `="01234"`).

I ran into this because Amazon Order Reporting was feeding me back a csv that contained equals signs before the initial quote in a few fields. I worked around it by removing them for now prior to parsing since I'm not parsing int anyway, but would properly implementing this "standard" be a good idea? Currently the parser chokes on those equals signs and errors out.

**Comment by wdavidw** [comment]
closing, feel free to re-open if necessary

**Comment by Crusader4Christ** [comment]
So, question is - how to parse the file with equals like:
`="Country Name",="Customer ID",="Customer First Name"`

**Comment by wdavidw** [comment]
Two choice:
- implement delimiter_start and delimiter_end as a pull request to this library
- post-parse your field after this module and remove the equal and quote signs, you could use stream-transform to do so
