### ISSUE TITLE
Error when number of columns is inconsistent

### ISSUE THREAD

**Issue by geniass** [wdavidw/node-csv-parse#73]
It seems reasonable to me to throw an error when the number of columns is inconsistent, such as the following CSV (first line is a header):
```
A,B,C
1,2,3
5,6
```
If the first column is missing from the last line, then all the subsequent columns get shifted over by one, and the parser fails silently.

**Comment by wdavidw** [comment]
closing after #74

**Comment by ktrzeciaknubisa** [comment]
That's a nice feature, however I would propose adding also a switch to be able to disable this. 

Previously (before this feature was implemented) I was able to fix the inconsistency within my wrapper to your parser **during the parsing** (e.g. by adding a null cell value or `columnX` column name - in case the inconsistency was found in header row. I was doing that in `parser.on('finish')`). This way I could import even inconsistent files.

Right now since the error is raised, my wrapping code is not even reached forcing me to provide consistent file **before the parsing**.

**Comment by wdavidw** [comment]
There is an option "relax_column_count", did you try it?

**Comment by ktrzeciaknubisa** [comment]
Oh, hell no :) Work now, thanks! Somehow I missed that update in the docs...

**Comment by Kostanos** [comment]
I think this parameter: `relax_column_count` should be true by default. From my experience, CSV around the word almost always have this inconsistency of columns, especially big sets of data.

**Comment by wdavidw** [comment]
I disagree, which doesn't mean you are not right. In any case, let's keep it the way it is now.
